# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: make-hs-template
version: '0.0.0'
github: "githubuser/make-hs-template"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new template package.
# description: make-hs-template is a new template package.
# category: Other

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - directory
  - filepath
  - unix
  source-dirs: src

executables:
  make-hs-template:
    source-dirs: app
    main: Main.hs
    dependencies:
    - base
    - make-hs-template
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  make-hs-template-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - make-hs-template
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  make-hs-template-test-suite:
    source-dirs: test
    main: Main.hs
    dependencies:
    - base
    - make-hs-template
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
